[project]
authors = [{ name = "quantity-dev contributors" }]
name = "metrology-apis"
requires-python = ">= 3.13"
version = "0.0.1.dev0"
dependencies = ["optype>=0.9.2,<0.10"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[tool.pixi.workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
metrology-apis = { path = "." }
optype = ">=0.9.2,<0.10"

[tool.pixi.feature.lint.dependencies]
basedpyright = "*"
basedmypy = "*"

[tool.pixi.feature.lint.tasks]
pyright = "basedpyright"
mypy = "mypy"
lint = { depends-on = ["mypy", "pyright"] }

[tool.pixi.environments]
lint = ["lint"]

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[tool.pixi.package.host-dependencies]
hatchling = "==1.27.0"


[tool.mypy]
files = ["src"]
python_version = "3.13"
warn_unused_configs = true
strict = true
enable_error_code = ["ignore-without-code", "truthy-bool"]


[tool.basedpyright]
include = ["src"]
pythonVersion = "3.13"
pythonPlatform = "All"
typeCheckingMode = "all"
