"""Metrology APIs."""

from typing import Final, Protocol, Self, override, runtime_checkable

import optype as op

__version__: Final = "0.0.1.dev0"
__all__ = ["__version__", "Dimension", "Quantity", "Unit"]


@runtime_checkable
class Dimension(Protocol):
    def __mul__(self, other: Self, /) -> Self: ...
    def __truediv__(self, other: Self, /) -> Self: ...
    def __pow__(self, other: int, /) -> Self: ...

    def __rmul__(self, other: Self, /) -> Self: ...
    def __rtruediv__(self, other: Self, /) -> Self: ...


@runtime_checkable
class Unit(Protocol):
    @property
    def dimension(self) -> Dimension: ...

    def __mul__(self, other: Self, /) -> Self: ...
    def __truediv__(self, other: Self, /) -> Self: ...
    def __pow__(self, other: int | float, /) -> Self: ...

    def __rmul__(self, other: Self, /) -> Self: ...
    def __rtruediv__(self, other: Self, /) -> Self: ...


@runtime_checkable
class Quantity[V, U: Unit](Protocol):
    @property
    def value(self) -> V: ...
    @property
    def unit(self) -> U: ...

    ### Dunder Methods
    def __ne__[B](self: "Quantity[V, U]", other: "Quantity[op.CanEq[V, B], U]", /) -> B: ...
    def __lt__[B](self: "Quantity[V, U]", other: "Quantity[op.CanOrd[V, B], U]", /) -> B: ...
    def __le__[B](self: "Quantity[V, U]", other: "Quantity[op.CanOrd[V, B], U]", /) -> B: ...
    def __gt__[B](self: "Quantity[V, U]", other: "Quantity[op.CanOrd[V, B], U]", /) -> B: ...
    def __ge__[B](self: "Quantity[V, U]", other: "Quantity[op.CanOrd[V, B], U]", /) -> B: ...

    def __pos__(self: "Quantity[V, U]") -> "Quantity[op.CanPos[V], U]": ...
    def __neg__(self: "Quantity[V, U]") -> "Quantity[op.CanNeg[V], U]": ...
    def __abs__(self: "Quantity[V, U]") -> "Quantity[op.CanAbs[V], U]": ...

    def __add__[B](self: "Quantity[V, U]", other: "Quantity[op.CanAdd[V, B], U]", /) -> "Quantity[op.CanAdd[V, B], U]": ...
    def __radd__[B](self: "Quantity[V, U]", other: "Quantity[op.CanAdd[V, B], U]", /) -> "Quantity[op.CanAdd[V, B], U]": ...
    def __sub__[B](self: "Quantity[V, U]", other: "Quantity[op.CanSub[V, B], U]", /) -> "Quantity[op.CanSub[V, B], U]": ...
    def __rsub__[B](self: "Quantity[V, U]", other: "Quantity[op.CanSub[V, B], U]", /) -> "Quantity[op.CanSub[V, B], U]": ...

    def __mul__[B](self: "Quantity[V, U]", other: "Quantity[op.CanMul[V, B], U]", /) -> "Quantity[op.CanMul[V, B], U]": ...
    def __rmul__[B](self: "Quantity[V, U]", other: "Quantity[op.CanMul[V, B], U]", /) -> "Quantity[op.CanMul[V, B], U]": ...
    def __truediv__[B](self: "Quantity[V, U]", other: "Quantity[op.CanDiv[V, B], U]", /) -> "Quantity[op.CanDiv[V, B], U]": ...
    def __rtruediv__[B](self: "Quantity[V, U]", other: "Quantity[op.CanDiv[V, B], U]", /) -> "Quantity[op.CanDiv[V, B], U]": ...

    def __pow__(self: "Quantity[V, U]", other: int | float, /) -> "Quantity[op.CanPow[V], U]": ...
    def __rpow__(self: "Quantity[V, U]", other: int | float, /) -> "Quantity[op.CanPow[V], U]": ...

    @override
    def __eq__[B](  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]
        self: "Quantity[V, U]", other: "Quantity[op.CanEq[V, B], U]", /
    ) -> B: ...
